[package]
name = "techpulse-usecase"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
techpulse-domain = { path = "../domain" }
techpulse-shared = { path = "../shared" }
async-trait = "0.1"
